spring:
  #  jackson:
  #    serialization:
  #      FAIL_ON_EMPTY_BEANS: true
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  redis:
    #host: 49.233.163.208
    host: 172.16.138.240
    port: 6379
    database: 5
    pool:
      max-active: 2000
      max-idle: 8
      max-wait: -1
      min-idle: 2
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/jsp/
  #      suffix: .jsp
  #      path-pattern: /static/**
  datasource:
    url: jdbc:mysql://39.106.157.58:3306/wuzu?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&allowMutiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size:  50Mb
      maxRequestSize: 50Mb
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxp.patMag.entity
  configuration:
    mapUnderscoreToCamelCase: true

expireTime: 7200
logExpireTime: 604800

file:
  accessPath: /upload/
  staticAccessPath: /upload/**
  uploadFolder: C://tmp/
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8